version: '3.9'
services:
  phpmyadmin-1:
    image: phpmyadmin:5.1
    restart: always
    ports:
      - '127.0.0.1:18000:80'
    environment:
      PMA_HOSTS: 192.168.15.100:13306
  phpmyadmin-2:
    image: phpmyadmin:5.1
    restart: always
    ports:
      - '127.0.0.1:28000:80'
    environment:
      PMA_HOSTS: 192.168.15.100:23306
  phpmyadmin-3:
    image: phpmyadmin:5.1
    restart: always
    ports:
      - '127.0.0.1:38000:80'
    environment:
      PMA_HOSTS: 192.168.15.100:33306
  
